[package]
name = "viper-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "viper"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
viper-core = { path = "../viper-core" }

[dev-dependencies]
assert_cmd = "2.0"
md5 = "0.7"
predicates = "3.1"
tempfile = "3.13"
